version: '3'
services:
  tekno_api:
    build: .
    ports:
      - '3434:3000'
    volumes:
      - './:/code'
    networks:
      - tekno_network
networks:
  tekno_network:
    external:
      name: tekno_network
